In [1]:
cd '/Volumes/iTunes/Projects/Analytics Course/ProjectTwo/Lesson 2/lahman-csv_2015-01-24'

/Volumes/iTunes/Projects/Analytics Course/ProjectTwo/Lesson 2/lahman-csv_2015-01-24

In [17]:
import pandas as pd
batting_file = 'Batting.csv'
master = 'Master.csv'

batting_data = pd.read_csv(batting_file)
master_data = pd.read_csv(master)

grouped_hits = batting_data['H'].groupby(batting_data['playerID']).sum().reset_index()
grouped_at_bats = batting_data['AB'].groupby(batting_data['playerID']).sum().reset_index()

grouped_hits['ratio'] = grouped_hits.H.div(grouped_at_bats.AB, axis='index')

master_data = master_data.merge(grouped_hits, on='playerID', how='left')

print master_data

        playerID  birthYear  birthMonth  birthDay birthCountry birthState  \
0      aardsda01     1981.0        12.0      27.0          USA         CO
1      aaronha01     1934.0         2.0       5.0          USA         AL
2      aaronto01     1939.0         8.0       5.0          USA         AL
3       aasedo01     1954.0         9.0       8.0          USA         CA
4       abadan01     1972.0         8.0      25.0          USA         FL
5       abadfe01     1985.0        12.0      17.0         D.R.  La Romana
6      abadijo01     1854.0        11.0       4.0          USA         PA
7      abbated01     1877.0         4.0      15.0          USA         PA
8      abbeybe01     1869.0        11.0      11.0          USA         VT
9      abbeych01     1866.0        10.0      14.0          USA         NE
10     abbotda01     1862.0         3.0      16.0          USA         OH
11     abbotfr01     1874.0        10.0      22.0          USA         OH
12     abbotgl01     1951.0         2.0      16.0          USA         AR
13     abbotje01     1972.0         8.0      17.0          USA         GA
14     abbotji01     1967.0         9.0      19.0          USA         MI
15     abbotku01     1969.0         6.0       2.0          USA         OH
16     abbotky01     1968.0         2.0      18.0          USA         MA
17     abbotod01     1888.0         9.0       5.0          USA         PA
18     abbotpa01     1967.0         9.0      15.0          USA         CA
19      aberal01     1927.0         7.0      31.0          USA         OH
20     abercda01     1850.0         1.0       2.0          USA         OK
21     abercre01     1980.0         7.0      15.0          USA         GA
22     abernbi01     1929.0         1.0      30.0          USA         CA
23     abernbr01     1977.0         9.0      23.0          USA         GA
24     abernte01     1921.0        10.0      30.0          USA         NC
25     abernte02     1933.0         3.0       6.0          USA         NC
26     abernwo01     1915.0         2.0       1.0          USA         NC
27     aberscl01     1921.0         8.0      28.0          USA         IL
28     ablesha01     1883.0        10.0       4.0          USA         TX
29     abnersh01     1966.0         6.0      17.0          USA         OH
...          ...        ...         ...       ...          ...        ...
18559  zimmejo01     1975.0         4.0      28.0          CAN         BC
18560  zimmejo02     1986.0         5.0      23.0          USA         WI
18561  zimmero01     1916.0         9.0      13.0          USA         PA
18562  zimmery01     1984.0         9.0      28.0          USA         NC
18563   zinkch01     1979.0         8.0      26.0          USA         CA
18564   zinkwa01     1898.0        11.0      21.0          USA         MA
18565   zinnfr01     1865.0        12.0      21.0          USA         PA
18566   zinngu01     1887.0         2.0      13.0          USA         WV
18567   zinnji01     1895.0         1.0      21.0          USA         AR
18568  zinsebi01     1918.0         1.0       6.0          USA         NY
18569  zinteal01     1968.0         5.0      19.0          USA         TX
18570  zipfebu01     1938.0        11.0      18.0          USA         IL
18571   ziskri01     1949.0         2.0       6.0          USA         NY
18572   zitoba01     1978.0         5.0      13.0          USA         NV
18573  zitzmbi01     1895.0        11.0      19.0          USA         NY
18574  zmiched01     1884.0        10.0       1.0          USA         OH
18575  zobribe01     1981.0         5.0      26.0          USA         IL
18576  zoccope01     1977.0         2.0       6.0          USA         NY
18577  zoldasa01     1918.0        12.0       8.0          USA         NY
18578  zoskyed01     1968.0         2.0      10.0          USA         CA
18579  zuberbi01     1913.0         3.0      26.0          USA         IA
18580  zuberjo01     1969.0        12.0      10.0          USA         CA
18581  zuletju01     1975.0         3.0      28.0       Panama     Panama
18582  zumayjo01     1984.0        11.0       9.0          USA         CA
18583  zuninmi01     1991.0         3.0      25.0          USA         FL
18584  zupcibo01     1966.0         8.0      18.0          USA         PA
18585   zupofr01     1939.0         8.0      29.0          USA         CA
18586  zuvelpa01     1958.0        10.0      31.0          USA         CA
18587  zuverge01     1924.0         8.0      20.0          USA         MI
18588  zwilldu01     1888.0        11.0       2.0          USA         MO

              birthCity  deathYear  deathMonth  deathDay    ...    weight  \
0                Denver        NaN         NaN       NaN    ...     205.0
1                Mobile        NaN         NaN       NaN    ...     180.0
2                Mobile     1984.0         8.0      16.0    ...     190.0
3                Orange        NaN         NaN       NaN    ...     190.0
4            Palm Beach        NaN         NaN       NaN    ...     184.0
5             La Romana        NaN         NaN       NaN    ...     220.0
6          Philadelphia     1905.0         5.0      17.0    ...     192.0
7               Latrobe     1957.0         1.0       6.0    ...     170.0
8                 Essex     1962.0         6.0      11.0    ...     175.0
9            Falls City     1926.0         4.0      27.0    ...     169.0
10              Portage     1930.0         2.0      13.0    ...     190.0
11           Versailles     1935.0         6.0      11.0    ...     180.0
12          Little Rock        NaN         NaN       NaN    ...     200.0
13              Atlanta        NaN         NaN       NaN    ...     190.0
14                Flint        NaN         NaN       NaN    ...     200.0
15           Zanesville        NaN         NaN       NaN    ...     180.0
16          Newburyport        NaN         NaN       NaN    ...     200.0
17            New Eagle     1933.0         4.0      13.0    ...     180.0
18             Van Nuys        NaN         NaN       NaN    ...     185.0
19            Cleveland     1993.0         5.0      20.0    ...     195.0
20          Fort Towson     1939.0        11.0      11.0    ...       NaN
21             Columbus        NaN         NaN       NaN    ...     215.0
22             Torrance     2006.0         2.0      19.0    ...     190.0
23              Atlanta        NaN         NaN       NaN    ...     185.0
24                Bynum     2001.0        11.0      16.0    ...     210.0
25              Stanley     2004.0        12.0      16.0    ...     215.0
26          Forest City     1994.0        12.0       5.0    ...     170.0
27              Chicago     1973.0         6.0      23.0    ...     200.0
28              Terrell     1951.0         2.0       8.0    ...     200.0
29             Hamilton        NaN         NaN       NaN    ...     190.0
...                 ...        ...         ...       ...    ...       ...
18559           Kelowna        NaN         NaN       NaN    ...     200.0
18560        Auburndale        NaN         NaN       NaN    ...     220.0
18561        Pine Grove     1991.0        11.0      22.0    ...     187.0
18562        Washington        NaN         NaN       NaN    ...     220.0
18563        Carmichael        NaN         NaN       NaN    ...     190.0
18564        Pittsfield     1964.0         6.0      12.0    ...     165.0
18565      Phoenixville     1936.0         5.0      12.0    ...     150.0
18566          Holbrook     1949.0        10.0       6.0    ...     170.0
18567            Benton     1991.0         2.0      26.0    ...     195.0
18568           Astoria     1993.0         2.0      16.0    ...     185.0
18569           El Paso        NaN         NaN       NaN    ...     200.0
18570        Belleville        NaN         NaN       NaN    ...     200.0
18571          Brooklyn        NaN         NaN       NaN    ...     200.0
18572         Las Vegas        NaN         NaN       NaN    ...     205.0
18573  Long Island City     1985.0         5.0      29.0    ...     175.0
18574         Cleveland     1950.0         8.0      20.0    ...     180.0
18575            Eureka        NaN         NaN       NaN    ...     210.0
18576             Bronx        NaN         NaN       NaN    ...     200.0
18577          Brooklyn     1966.0         8.0      25.0    ...     185.0
18578          Whittier        NaN         NaN       NaN    ...     175.0
18579      Middle Amana     1982.0        11.0       2.0    ...     195.0
18580            Encino        NaN         NaN       NaN    ...     190.0
18581            Panama        NaN         NaN       NaN    ...     230.0
18582       Chula Vista        NaN         NaN       NaN    ...     215.0
18583        Cape Coral        NaN         NaN       NaN    ...     220.0
18584        Pittsburgh        NaN         NaN       NaN    ...     220.0
18585     San Francisco     2005.0         3.0      25.0    ...     182.0
18586         San Mateo        NaN         NaN       NaN    ...     173.0
18587           Holland     2014.0         9.0       8.0    ...     195.0
18588         St. Louis     1978.0         3.0      27.0    ...     160.0

      height bats throws       debut   finalGame   retroID    bbrefID       H  \
0       75.0    R      R    4/6/2004   9/28/2013  aardd001  aardsda01     0.0
1       72.0    R      R   4/13/1954   10/3/1976  aaroh101  aaronha01  3771.0
2       75.0    R      R   4/10/1962   9/26/1971  aarot101  aaronto01   216.0
3       75.0    R      R   7/26/1977   10/3/1990  aased001   aasedo01     0.0
4       73.0    L      L   9/10/2001   4/13/2006  abada001   abadan01     2.0
5       73.0    L      L   7/28/2010   9/27/2014  abadf001   abadfe01     1.0
6       72.0    R      R  1875-04-26  1875-06-10  abadj101  abadijo01    11.0
7       71.0    R      R  1897-09-04   9/15/1910  abbae101  abbated01   772.0
8       71.0    R      R  1892-06-14  1896-09-23  abbeb101  abbeybe01    38.0
9       68.0    L      L  1893-08-16  1897-08-19  abbec101  abbeych01   492.0
10      71.0    R      R  1890-04-19  1890-05-23  abbod101  abbotda01     1.0
11      70.0    R      R   4/25/1903   9/20/1905  abbof101  abbotfr01   107.0
12      78.0    R      R   7/29/1973    8/8/1984  abbog001  abbotgl01     0.0
13      74.0    R      L   6/10/1997   9/29/2001  abboj002  abbotje01   157.0
14      75.0    L      L    4/8/1989   7/21/1999  abboj001  abbotji01     2.0
15      71.0    R      R    9/7/1993   4/13/2001  abbok002  abbotku01   523.0
16      76.0    L      L   9/10/1991   8/24/1996  abbok001  abbotky01     3.0
17      74.0    R      R   9/10/1910  10/15/1910  abboo101  abbotod01    13.0
18      75.0    R      R   8/21/1990    8/7/2004  abbop001  abbotpa01     5.0
19      74.0    L      L   9/15/1950   9/11/1957  abera101   aberal01    14.0
20       NaN  NaN    NaN  1871-10-21  1871-10-21  aberd101  abercda01     0.0
21      75.0    R      R    4/4/2006   9/28/2008  aberr001  abercre01    86.0
22      70.0    R      R   9/27/1952   9/27/1952  aberb101  abernbi01     0.0
23      73.0    R      R   6/25/2001   9/29/2005  aberb001  abernbr01   212.0
24      74.0    R      L   9/19/1942   4/29/1944  abert102  abernte01     1.0
25      76.0    R      R   4/13/1955   9/30/1972  abert101  abernte02    25.0
26      72.0    L      L   7/28/1946   4/17/1947  aberw101  abernwo01     0.0
27      72.0    R      R   7/18/1947    5/9/1949  aberc101  aberscl01    45.0
28      74.0    R      L    9/4/1905    5/5/1911  ableh101  ablesha01     0.0
29      73.0    R      R    9/8/1987   10/3/1992  abnes001  abnersh01   191.0
...      ...  ...    ...         ...         ...       ...        ...     ...
18559   72.0    R      L   5/17/1999    7/2/1999  zimmj002  zimmejo01     0.0
18560   74.0    R      R   4/20/2009   9/28/2014  zimmj003  zimmejo02    44.0
18561   74.0    L      L   8/27/1945   9/30/1945  zimmr101  zimmero01    27.0
18562   75.0    R      R    9/1/2005   9/28/2014  zimmr001  zimmery01  1326.0
18563   73.0    R      R   8/12/2008   8/12/2008  zinkc001   zinkch01     0.0
18564   72.0    R      R    7/6/1921   7/19/1921  zinkw101   zinkwa01     0.0
18565   68.0  NaN    NaN  1888-04-18  1888-05-03  zinnf101   zinnfr01     0.0
18566   70.0    L      R   9/11/1911   9/16/1915  zinng101   zinngu01   297.0
18567   72.0    L      R    9/4/1919   8/25/1929  zinnj101   zinnji01    34.0
18568   73.0    R      R   8/19/1944   8/26/1944  zinsb101  zinsebi01     0.0
18569   74.0    B      R   6/18/2002   10/3/2004  zinta001  zinteal01    13.0
18570   75.0    L      R   7/26/1961   9/30/1962  zipfb101  zipfebu01    78.0
18571   73.0    R      R    9/8/1971   9/21/1983  ziskr101   ziskri01  1477.0
18572   74.0    L      L   7/22/2000   9/29/2013  zitob001   zitoba01    35.0
18573   70.0    R      R   4/27/1919   9/25/1929  zitzb101  zitzmbi01   268.0
18574   72.0    L      L   7/23/1910    6/1/1911  zmice101  zmiched01     1.0
18575   75.0    B      R    8/1/2006   9/27/2014  zobrb001  zobribe01  1016.0
18576   74.0    L      R    9/5/2003   9/28/2003  zoccp001  zoccope01     4.0
18577   71.0    L      L   5/13/1944   8/26/1952  zolds101  zoldasa01    50.0
18578   72.0    R      R    9/2/1991   10/1/2000  zoske001  zoskyed01     8.0
18579   74.0    R      R   9/16/1936   9/23/1947  zubeb101  zuberbi01    31.0
18580   73.0    L      L   4/19/1996   9/27/1998  zubej001  zuberjo01    34.0
18581   78.0    R      R    4/6/2000   6/25/2001  zulej001  zuletju01    43.0
18582   75.0    R      R    4/3/2006   6/28/2010  zumaj001  zumayjo01     0.0
18583   74.0    R      R   6/12/2013   9/28/2014  zunim001  zuninmi01   124.0
18584   76.0    R      R    9/7/1991    8/4/1994  zupcb001  zupcibo01   199.0
18585   71.0    L      R    7/1/1957    5/9/1961  zupof101   zupofr01     3.0
18586   72.0    R      R    9/4/1982    5/2/1991  zuvep001  zuvelpa01   109.0
18587   76.0    R      R   4/21/1951   6/15/1959  zuveg101  zuverge01    21.0
18588   66.0    L      L   8/14/1910   7/12/1916  zwild101  zwilldu01   364.0

          ratio
0      0.000000
1      0.304998
2      0.228814
3      0.000000
4      0.095238
5      0.125000
6      0.224490
7      0.253614
8      0.168889
9      0.280982
10     0.142857
11     0.208577
12          NaN
13     0.263423
14     0.095238
15     0.255871
16     0.096774
17     0.185714
18     0.250000
19     0.140000
20     0.000000
21     0.222798
22     0.000000
23     0.244240
24     0.200000
25     0.138122
26     0.000000
27     0.251397
28     0.000000
29     0.227381
...         ...
18559       NaN
18560  0.171206
18561  0.275510
18562  0.285591
18563       NaN
18564  0.000000
18565  0.000000
18566  0.269266
18567  0.283333
18568       NaN
18569  0.166667
18570  0.220339
18571  0.287131
18572  0.101744
18573  0.266932
18574  0.058824
18575  0.263896
18576  0.108108
18577  0.174825
18578  0.160000
18579  0.135371
18580  0.250000
18581  0.247126
18582       NaN
18583  0.202946
18584  0.250314
18585  0.166667
18586  0.221996
18587  0.147887
18588  0.284375

[18589 rows x 26 columns]

In [5]:
import pandas as pd
import numpy as np
batting_file = 'Batting.csv'

Batting_stats = pd.read_csv(batting_file)

print Batting_stats
plate_appearance_frame  = Batting_stats[(np.isfinite(Batting_stats['AB'])) & (Batting_stats.AB!=0) & (Batting_stats.BB !=0) &  (Batting_stats.IBB !=0) &  (Batting_stats.HBP !=0) ]

        playerID  yearID  stint teamID lgID    G     AB     R      H    2B  \
0      abercda01    1871      1    TRO  NaN    1    4.0   0.0    0.0   0.0
1       addybo01    1871      1    RC1  NaN   25  118.0  30.0   32.0   6.0
2      allisar01    1871      1    CL1  NaN   29  137.0  28.0   40.0   4.0
3      allisdo01    1871      1    WS3  NaN   27  133.0  28.0   44.0  10.0
4      ansonca01    1871      1    RC1  NaN   25  120.0  29.0   39.0  11.0
5      armstbo01    1871      1    FW1  NaN   12   49.0   9.0   11.0   2.0
6      barkeal01    1871      1    RC1  NaN    1    4.0   0.0    1.0   0.0
7      barnero01    1871      1    BS1  NaN   31  157.0  66.0   63.0  10.0
8      barrebi01    1871      1    FW1  NaN    1    5.0   1.0    1.0   1.0
9      barrofr01    1871      1    BS1  NaN   18   86.0  13.0   13.0   2.0
10      bassjo01    1871      1    CL1  NaN   22   89.0  18.0   27.0   1.0
11     battijo01    1871      1    CL1  NaN    1    3.0   0.0    0.0   0.0
12     bealsto01    1871      1    WS3  NaN   10   36.0   6.0    7.0   0.0
13     beaveed01    1871      1    TRO  NaN    3   15.0   7.0    6.0   0.0
14     bechtge01    1871      1    PH1  NaN   20   94.0  24.0   33.0   9.0
15     bellast01    1871      1    TRO  NaN   29  128.0  26.0   32.0   3.0
16     berkena01    1871      1    PH1  NaN    1    4.0   0.0    0.0   0.0
17     berryto01    1871      1    PH1  NaN    1    4.0   0.0    1.0   0.0
18     berthha01    1871      1    WS3  NaN   17   73.0  17.0   17.0   1.0
19     biermch01    1871      1    FW1  NaN    1    2.0   0.0    0.0   0.0
20      birdge01    1871      1    RC1  NaN   25  106.0  19.0   28.0   2.0
21     birdsda01    1871      1    BS1  NaN   29  152.0  51.0   46.0   3.0
22     brainas01    1871      1    WS3  NaN   30  134.0  24.0   30.0   4.0
23     brannmi01    1871      1    CH1  NaN    3   14.0   2.0    1.0   0.0
24     burrohe01    1871      1    WS3  NaN   12   63.0  11.0   15.0   2.0
25     careyto01    1871      1    FW1  NaN   19   87.0  16.0   20.0   2.0
26     carleji01    1871      1    CL1  NaN   29  127.0  31.0   32.0   8.0
27      conefr01    1871      1    BS1  NaN   19   77.0  17.0   20.0   3.0
28     connone01    1871      1    TRO  NaN    7   33.0   6.0    7.0   0.0
29     cravebi01    1871      1    TRO  NaN   27  118.0  26.0   38.0   8.0
...          ...     ...    ...    ...  ...  ...    ...   ...    ...   ...
99816  wilsojo03    2014      1    TEX   AL   24   67.0   7.0   16.0   4.0
99817  wilsoju10    2014      1    PIT   NL   70    1.0   0.0    0.0   0.0
99818  withrch01    2014      1    LAN   NL   20    0.0   0.0    0.0   0.0
99819   wolfra02    2014      1    MIA   NL    6    7.0   0.0    1.0   0.0
99820   wongko01    2014      1    SLN   NL  113  402.0  52.0  100.0  14.0
99821   woodal02    2014      1    ATL   NL   35   41.0   1.0    3.0   0.0
99822   woodbl01    2014      1    CLE   AL    7    0.0   0.0    0.0   0.0
99823   woodtr01    2014      1    CHN   NL   41   56.0   9.0   13.0   2.0
99824  wootero01    2014      1    MIL   NL   40    0.0   0.0    0.0   0.0
99825  workmbr01    2014      1    BOS   AL   19    3.0   0.0    0.0   0.0
99826  worleva01    2014      1    PIT   NL   20   32.0   1.0    2.0   1.0
99827  worthda01    2014      1    DET   AL   20   42.0   5.0    7.0   1.0
99828  wrighda03    2014      1    NYN   NL  134  535.0  54.0  144.0  30.0
99829  wrighja01    2014      1    LAN   NL   61    5.0   0.0    0.0   0.0
99830  wrighst01    2014      1    BOS   AL    6    0.0   0.0    0.0   0.0
99831  wrighwe01    2014      1    CHN   NL   58    0.0   0.0    0.0   0.0
99832  yateski01    2014      1    TBA   AL   37    0.0   0.0    0.0   0.0
99833  yelicch01    2014      1    MIA   NL  144  582.0  94.0  165.0  30.0
99834   ynoara01    2014      1    COL   NL   19   67.0   5.0   23.0   6.0
99835  youngch03    2014      1    SEA   AL   30    1.0   0.0    0.0   0.0
99836  youngch04    2014      1    NYN   NL   88  254.0  31.0   52.0  12.0
99837  youngch04    2014      2    NYA   AL   23   71.0   9.0   20.0   8.0
99838  youngde03    2014      1    BAL   AL   83  242.0  27.0   73.0  11.0
99839  younger03    2014      1    NYN   NL  100  280.0  48.0   64.0  10.0
99840   zeidjo01    2014      1    HOU   AL   23    1.0   0.0    0.0   0.0
99841  zieglbr01    2014      1    ARI   NL   68    1.0   0.0    0.0   0.0
99842  zimmejo02    2014      1    WAS   NL   32   55.0   3.0   10.0   1.0
99843  zimmery01    2014      1    WAS   NL   61  214.0  26.0   60.0  19.0
99844  zobribe01    2014      1    TBA   AL  146  570.0  83.0  155.0  34.0
99845  zuninmi01    2014      1    SEA   AL  131  438.0  51.0   87.0  20.0

       ...    RBI    SB   CS    BB     SO  IBB   HBP   SH   SF  GIDP
0      ...    0.0   0.0  0.0   0.0    0.0  NaN   NaN  NaN  NaN   NaN
1      ...   13.0   8.0  1.0   4.0    0.0  NaN   NaN  NaN  NaN   NaN
2      ...   19.0   3.0  1.0   2.0    5.0  NaN   NaN  NaN  NaN   NaN
3      ...   27.0   1.0  1.0   0.0    2.0  NaN   NaN  NaN  NaN   NaN
4      ...   16.0   6.0  2.0   2.0    1.0  NaN   NaN  NaN  NaN   NaN
5      ...    5.0   0.0  1.0   0.0    1.0  NaN   NaN  NaN  NaN   NaN
6      ...    2.0   0.0  0.0   1.0    0.0  NaN   NaN  NaN  NaN   NaN
7      ...   34.0  11.0  6.0  13.0    1.0  NaN   NaN  NaN  NaN   NaN
8      ...    1.0   0.0  0.0   0.0    0.0  NaN   NaN  NaN  NaN   NaN
9      ...   11.0   1.0  0.0   0.0    0.0  NaN   NaN  NaN  NaN   NaN
10     ...   18.0   0.0  1.0   3.0    4.0  NaN   NaN  NaN  NaN   NaN
11     ...    0.0   0.0  0.0   1.0    0.0  NaN   NaN  NaN  NaN   NaN
12     ...    1.0   2.0  0.0   2.0    0.0  NaN   NaN  NaN  NaN   NaN
13     ...    5.0   2.0  0.0   0.0    0.0  NaN   NaN  NaN  NaN   NaN
14     ...   21.0   4.0  0.0   2.0    2.0  NaN   NaN  NaN  NaN   NaN
15     ...   23.0   4.0  4.0   9.0    2.0  NaN   NaN  NaN  NaN   NaN
16     ...    0.0   0.0  0.0   0.0    3.0  NaN   NaN  NaN  NaN   NaN
17     ...    0.0   0.0  0.0   0.0    0.0  NaN   NaN  NaN  NaN   NaN
18     ...    8.0   3.0  1.0   4.0    2.0  NaN   NaN  NaN  NaN   NaN
19     ...    0.0   0.0  0.0   1.0    0.0  NaN   NaN  NaN  NaN   NaN
20     ...   13.0   1.0  0.0   3.0    2.0  NaN   NaN  NaN  NaN   NaN
21     ...   24.0   6.0  0.0   4.0    4.0  NaN   NaN  NaN  NaN   NaN
22     ...   21.0   4.0  0.0   7.0    2.0  NaN   NaN  NaN  NaN   NaN
23     ...    0.0   0.0  0.0   0.0    0.0  NaN   NaN  NaN  NaN   NaN
24     ...   14.0   0.0  0.0   1.0    1.0  NaN   NaN  NaN  NaN   NaN
25     ...   10.0   5.0  0.0   2.0    1.0  NaN   NaN  NaN  NaN   NaN
26     ...   18.0   2.0  1.0   8.0    3.0  NaN   NaN  NaN  NaN   NaN
27     ...   16.0  12.0  1.0   8.0    2.0  NaN   NaN  NaN  NaN   NaN
28     ...    2.0   0.0  0.0   0.0    0.0  NaN   NaN  NaN  NaN   NaN
29     ...   26.0   6.0  3.0   3.0    0.0  NaN   NaN  NaN  NaN   NaN
...    ...    ...   ...  ...   ...    ...  ...   ...  ...  ...   ...
99816  ...    8.0   1.0  0.0   2.0   14.0  0.0   1.0  2.0  0.0   3.0
99817  ...    0.0   0.0  0.0   0.0    1.0  0.0   0.0  0.0  0.0   0.0
99818  ...    0.0   0.0  0.0   0.0    0.0  0.0   0.0  0.0  0.0   0.0
99819  ...    0.0   0.0  0.0   0.0    1.0  0.0   0.0  0.0  0.0   0.0
99820  ...   42.0  20.0  4.0  21.0   71.0  3.0   4.0  5.0  1.0  12.0
99821  ...    2.0   0.0  0.0   2.0   28.0  0.0   0.0  5.0  0.0   0.0
99822  ...    0.0   0.0  0.0   0.0    0.0  0.0   0.0  0.0  0.0   0.0
99823  ...   10.0   0.0  0.0   1.0   17.0  0.0   2.0  7.0  0.0   1.0
99824  ...    0.0   0.0  0.0   0.0    0.0  0.0   0.0  0.0  0.0   0.0
99825  ...    0.0   0.0  0.0   0.0    3.0  0.0   0.0  1.0  0.0   0.0
99826  ...    0.0   0.0  0.0   1.0   17.0  0.0   0.0  5.0  0.0   0.0
99827  ...    5.0   0.0  1.0   2.0   12.0  0.0   1.0  0.0  1.0   1.0
99828  ...   63.0   8.0  5.0  42.0  113.0  5.0   4.0  0.0  5.0  22.0
99829  ...    0.0   0.0  0.0   0.0    3.0  0.0   0.0  1.0  0.0   0.0
99830  ...    0.0   0.0  0.0   0.0    0.0  0.0   0.0  0.0  0.0   0.0
99831  ...    0.0   0.0  0.0   0.0    0.0  0.0   0.0  0.0  0.0   0.0
99832  ...    0.0   0.0  0.0   0.0    0.0  0.0   0.0  0.0  0.0   0.0
99833  ...   54.0  21.0  7.0  70.0  137.0  3.0   3.0  3.0  2.0   9.0
99834  ...   13.0   0.0  0.0   4.0    9.0  0.0   0.0  0.0  0.0   1.0
99835  ...    0.0   0.0  0.0   0.0    0.0  0.0   0.0  0.0  0.0   0.0
99836  ...   28.0   7.0  3.0  25.0   54.0  2.0   4.0  1.0  3.0   3.0
99837  ...   10.0   1.0  0.0   7.0   16.0  0.0   1.0  0.0  0.0   0.0
99838  ...   30.0   2.0  0.0  10.0   51.0  0.0   3.0  0.0  0.0   6.0
99839  ...   17.0  30.0  6.0  24.0   60.0  1.0   5.0  5.0  2.0   2.0
99840  ...    0.0   0.0  0.0   0.0    1.0  0.0   0.0  0.0  0.0   0.0
99841  ...    0.0   0.0  0.0   0.0    1.0  0.0   0.0  0.0  0.0   0.0
99842  ...    1.0   0.0  0.0   2.0   21.0  0.0   0.0  9.0  1.0   0.0
99843  ...   38.0   0.0  0.0  22.0   37.0  0.0   0.0  0.0  4.0   6.0
99844  ...   52.0  10.0  5.0  75.0   84.0  4.0   1.0  2.0  6.0   8.0
99845  ...   60.0   0.0  3.0  17.0  158.0  1.0  17.0  0.0  4.0  12.0

[99846 rows x 22 columns]

In [6]:
print plate_appearance_frame

        playerID  yearID  stint teamID lgID    G     AB      R      H    2B  \
1       addybo01    1871      1    RC1  NaN   25  118.0   30.0   32.0   6.0
2      allisar01    1871      1    CL1  NaN   29  137.0   28.0   40.0   4.0
4      ansonca01    1871      1    RC1  NaN   25  120.0   29.0   39.0  11.0
6      barkeal01    1871      1    RC1  NaN    1    4.0    0.0    1.0   0.0
7      barnero01    1871      1    BS1  NaN   31  157.0   66.0   63.0  10.0
10      bassjo01    1871      1    CL1  NaN   22   89.0   18.0   27.0   1.0
11     battijo01    1871      1    CL1  NaN    1    3.0    0.0    0.0   0.0
12     bealsto01    1871      1    WS3  NaN   10   36.0    6.0    7.0   0.0
14     bechtge01    1871      1    PH1  NaN   20   94.0   24.0   33.0   9.0
15     bellast01    1871      1    TRO  NaN   29  128.0   26.0   32.0   3.0
18     berthha01    1871      1    WS3  NaN   17   73.0   17.0   17.0   1.0
19     biermch01    1871      1    FW1  NaN    1    2.0    0.0    0.0   0.0
20      birdge01    1871      1    RC1  NaN   25  106.0   19.0   28.0   2.0
21     birdsda01    1871      1    BS1  NaN   29  152.0   51.0   46.0   3.0
22     brainas01    1871      1    WS3  NaN   30  134.0   24.0   30.0   4.0
24     burrohe01    1871      1    WS3  NaN   12   63.0   11.0   15.0   2.0
25     careyto01    1871      1    FW1  NaN   19   87.0   16.0   20.0   2.0
26     carleji01    1871      1    CL1  NaN   29  127.0   31.0   32.0   8.0
27      conefr01    1871      1    BS1  NaN   19   77.0   17.0   20.0   3.0
29     cravebi01    1871      1    TRO  NaN   27  118.0   26.0   38.0   8.0
30     cuthbne01    1871      1    PH1  NaN   28  150.0   47.0   37.0   7.0
31     deaneha01    1871      1    FW1  NaN    6   22.0    3.0    4.0   0.0
32     donnepe01    1871      1    FW1  NaN    9   34.0    7.0    7.0   1.0
33     duffyed01    1871      1    CH1  NaN   26  121.0   30.0   28.0   5.0
34     eggleda01    1871      1    NY2  NaN   33  147.0   37.0   47.0   7.0
36     fergubo01    1871      1    NY2  NaN   33  158.0   30.0   38.0   6.0
37     fishech01    1871      1    RC1  NaN   25  123.0   24.0   28.0   3.0
38     fislewe01    1871      1    PH1  NaN   28  147.0   43.0   41.0   8.0
40     flowedi01    1871      1    TRO  NaN   21  105.0   39.0   33.0   5.0
41     flynncl01    1871      1    TRO  NaN   29  142.0   43.0   48.0   6.0
...          ...     ...    ...    ...  ...  ...    ...    ...    ...   ...
99689  sweenry01    2014      1    CHN   NL   77  207.0   22.0   52.0   9.0
99701  teixema01    2014      1    NYA   AL  123  440.0   56.0   95.0  14.0
99702  tejadru01    2014      1    NYN   NL  119  355.0   30.0   84.0  11.0
99728  troutmi01    2014      1    LAA   AL  157  602.0  115.0  173.0  39.0
99729  trumbma01    2014      1    ARI   NL   88  328.0   37.0   77.0  15.0
99731  tulowtr01    2014      1    COL   NL   91  315.0   71.0  107.0  18.0
99734  turneju01    2014      1    LAN   NL  109  288.0   46.0   98.0  21.0
99738  uptonbj01    2014      1    ATL   NL  141  519.0   67.0  108.0  19.0
99739  uptonju01    2014      1    ATL   NL  154  566.0   77.0  153.0  34.0
99740  uribeju01    2014      1    LAN   NL  103  386.0   36.0  120.0  23.0
99741  utleych01    2014      1    PHI   NL  155  589.0   74.0  159.0  36.0
99742  valaich01    2014      1    CHN   NL   44  121.0   10.0   28.0   4.0
99743  valbulu01    2014      1    CHN   NL  149  478.0   68.0  119.0  33.0
99751  vargake01    2014      1    MIN   AL   53  215.0   26.0   59.0  10.0
99755  venabwi01    2014      1    SDN   NL  146  406.0   47.0   91.0  13.0
99761  vicieda01    2014      1    CHA   AL  145  523.0   65.0  121.0  22.0
99764  villajo01    2014      1    HOU   AL   87  263.0   31.0   55.0  13.0
99769   vogtst01    2014      1    OAK   AL   84  269.0   26.0   75.0  10.0
99771  vottojo01    2014      1    CIN   NL   62  220.0   32.0   56.0  16.0
99778  walkene01    2014      1    PIT   NL  137  512.0   74.0  139.0  25.0
99785  watkilo01    2014      1    CHN   NL   31   65.0   10.0   16.0   3.0
99794  werthja01    2014      1    WAS   NL  147  534.0   85.0  156.0  37.0
99810  willijo03    2014      1    MIN   AL   68  224.0   34.0   47.0   5.0
99820   wongko01    2014      1    SLN   NL  113  402.0   52.0  100.0  14.0
99828  wrighda03    2014      1    NYN   NL  134  535.0   54.0  144.0  30.0
99833  yelicch01    2014      1    MIA   NL  144  582.0   94.0  165.0  30.0
99836  youngch04    2014      1    NYN   NL   88  254.0   31.0   52.0  12.0
99839  younger03    2014      1    NYN   NL  100  280.0   48.0   64.0  10.0
99844  zobribe01    2014      1    TBA   AL  146  570.0   83.0  155.0  34.0
99845  zuninmi01    2014      1    SEA   AL  131  438.0   51.0   87.0  20.0

       ...     RBI    SB   CS    BB     SO   IBB   HBP   SH    SF  GIDP
1      ...    13.0   8.0  1.0   4.0    0.0   NaN   NaN  NaN   NaN   NaN
2      ...    19.0   3.0  1.0   2.0    5.0   NaN   NaN  NaN   NaN   NaN
4      ...    16.0   6.0  2.0   2.0    1.0   NaN   NaN  NaN   NaN   NaN
6      ...     2.0   0.0  0.0   1.0    0.0   NaN   NaN  NaN   NaN   NaN
7      ...    34.0  11.0  6.0  13.0    1.0   NaN   NaN  NaN   NaN   NaN
10     ...    18.0   0.0  1.0   3.0    4.0   NaN   NaN  NaN   NaN   NaN
11     ...     0.0   0.0  0.0   1.0    0.0   NaN   NaN  NaN   NaN   NaN
12     ...     1.0   2.0  0.0   2.0    0.0   NaN   NaN  NaN   NaN   NaN
14     ...    21.0   4.0  0.0   2.0    2.0   NaN   NaN  NaN   NaN   NaN
15     ...    23.0   4.0  4.0   9.0    2.0   NaN   NaN  NaN   NaN   NaN
18     ...     8.0   3.0  1.0   4.0    2.0   NaN   NaN  NaN   NaN   NaN
19     ...     0.0   0.0  0.0   1.0    0.0   NaN   NaN  NaN   NaN   NaN
20     ...    13.0   1.0  0.0   3.0    2.0   NaN   NaN  NaN   NaN   NaN
21     ...    24.0   6.0  0.0   4.0    4.0   NaN   NaN  NaN   NaN   NaN
22     ...    21.0   4.0  0.0   7.0    2.0   NaN   NaN  NaN   NaN   NaN
24     ...    14.0   0.0  0.0   1.0    1.0   NaN   NaN  NaN   NaN   NaN
25     ...    10.0   5.0  0.0   2.0    1.0   NaN   NaN  NaN   NaN   NaN
26     ...    18.0   2.0  1.0   8.0    3.0   NaN   NaN  NaN   NaN   NaN
27     ...    16.0  12.0  1.0   8.0    2.0   NaN   NaN  NaN   NaN   NaN
29     ...    26.0   6.0  3.0   3.0    0.0   NaN   NaN  NaN   NaN   NaN
30     ...    30.0  16.0  2.0  10.0    2.0   NaN   NaN  NaN   NaN   NaN
31     ...     2.0   0.0  0.0   2.0    0.0   NaN   NaN  NaN   NaN   NaN
32     ...     3.0   0.0  0.0   1.0    2.0   NaN   NaN  NaN   NaN   NaN
33     ...    15.0  11.0  4.0   3.0    2.0   NaN   NaN  NaN   NaN   NaN
34     ...    18.0  14.0  3.0   4.0    3.0   NaN   NaN  NaN   NaN   NaN
36     ...    25.0   4.0  4.0   3.0    2.0   NaN   NaN  NaN   NaN   NaN
37     ...    22.0   1.0  2.0   3.0    1.0   NaN   NaN  NaN   NaN   NaN
38     ...    16.0   6.0  3.0   3.0    2.0   NaN   NaN  NaN   NaN   NaN
40     ...    18.0   8.0  2.0   4.0    0.0   NaN   NaN  NaN   NaN   NaN
41     ...    27.0   3.0  3.0   4.0    2.0   NaN   NaN  NaN   NaN   NaN
...    ...     ...   ...  ...   ...    ...   ...   ...  ...   ...   ...
99689  ...    20.0   0.0  0.0  15.0   33.0   2.0   1.0  2.0   1.0   4.0
99701  ...    62.0   1.0  1.0  58.0  109.0   3.0   6.0  0.0   4.0  13.0
99702  ...    34.0   1.0  2.0  50.0   73.0  11.0   8.0  4.0   2.0   8.0
99728  ...   111.0  16.0  2.0  83.0  184.0   6.0  10.0  0.0  10.0   6.0
99729  ...    61.0   2.0  3.0  28.0   89.0   3.0   1.0  0.0   5.0   8.0
99731  ...    52.0   1.0  1.0  50.0   57.0   4.0   5.0  0.0   5.0   4.0
99734  ...    43.0   6.0  1.0  28.0   58.0   1.0   4.0  0.0   2.0   6.0
99738  ...    35.0  20.0  7.0  57.0  173.0   5.0   1.0  3.0   2.0   6.0
99739  ...   102.0   8.0  4.0  60.0  171.0   1.0   6.0  0.0   8.0  10.0
99740  ...    54.0   0.0  1.0  15.0   77.0   2.0   1.0  0.0   2.0  15.0
99741  ...    78.0  10.0  1.0  53.0   85.0  12.0  13.0  0.0   9.0   8.0
99742  ...    13.0   1.0  0.0   7.0   35.0   1.0   2.0  0.0   1.0   5.0
99743  ...    51.0   1.0  2.0  65.0  113.0   4.0   2.0  1.0   1.0   8.0
99751  ...    38.0   0.0  0.0  12.0   63.0   2.0   3.0  0.0   4.0   5.0
99755  ...    33.0  11.0  6.0  33.0  107.0   2.0   4.0  3.0   2.0   6.0
99761  ...    58.0   0.0  1.0  32.0  122.0   3.0   5.0  0.0   3.0  19.0
99764  ...    27.0  17.0  4.0  19.0   80.0   1.0   2.0  4.0   1.0   4.0
99769  ...    35.0   1.0  0.0  16.0   39.0   2.0   1.0  0.0   1.0   2.0
99771  ...    23.0   1.0  1.0  47.0   49.0   2.0   3.0  0.0   2.0   5.0
99778  ...    76.0   2.0  2.0  45.0   88.0   2.0  11.0  1.0   2.0  12.0
99785  ...     6.0   1.0  0.0   1.0   16.0   1.0   1.0  1.0   0.0   0.0
99794  ...    82.0   9.0  1.0  83.0  113.0   3.0   9.0  0.0   3.0   9.0
99810  ...    34.0   1.0  0.0  42.0   78.0   3.0   7.0  0.0   5.0   2.0
99820  ...    42.0  20.0  4.0  21.0   71.0   3.0   4.0  5.0   1.0  12.0
99828  ...    63.0   8.0  5.0  42.0  113.0   5.0   4.0  0.0   5.0  22.0
99833  ...    54.0  21.0  7.0  70.0  137.0   3.0   3.0  3.0   2.0   9.0
99836  ...    28.0   7.0  3.0  25.0   54.0   2.0   4.0  1.0   3.0   3.0
99839  ...    17.0  30.0  6.0  24.0   60.0   1.0   5.0  5.0   2.0   2.0
99844  ...    52.0  10.0  5.0  75.0   84.0   4.0   1.0  2.0   6.0   8.0
99845  ...    60.0   0.0  3.0  17.0  158.0   1.0  17.0  0.0   4.0  12.0

[28673 rows x 22 columns]